### ISSUE TITLE
Not found the declaration of models

### ISSUE THREAD

**Issue by vellichorw** [haoni0812/MDA#1]
Hi,
where is the declaration of models in [`from models import PDA, Model_AE`]?
[https://github.com/haoni0812/MDA/blob/4ea0263bbcdc483263674979c47c9bcd13f08e8c/tools/train_net.py#L14](url)

**Comment by zhennaziyu** [comment]
> Hi, where is the declaration of models in [`from models import PDA, Model_AE`]? [https://github.com/haoni0812/MDA/blob/4ea0263bbcdc483263674979c47c9bcd13f08e8c/tools/train_net.py#L14](url)

Yes, I also cannot find the declaration of models.

**Comment by ReIDkj** [comment]
yes， the same question I meet when import PDA, Model_AE

**Comment by NoaBrazilay** [comment]
I also cannot find the declaration of models  PDA, Model_AE

**Comment by BoomShakaY** [comment]
Me too. The model files are missing, which is very confusing.

**Comment by haoni0812** [comment]
Thank you for your attention to this work. We mentioned the structure of the model PDA in Section 4.2. "Both the encoder and decoder are composed of three fully connected layers, and the dimension of the latent embedding is set to 64." Refer to [VAE](https://github.com/AntixK/PyTorch-VAE/blob/master/models/vanilla_vae.py) for the implementation.  The KL divergence is replaced by the Wasserstein distance.  We have further improved MDA and will publish our new work soon.

**Comment by mumumu77** [comment]
Could you share the model PDA?
I make a code like above VAE but have a following error.
https://github.com/haoni0812/MDA/blob/8a6d2eb6331d51abd5501c00fad9e2b4cfac6b7a/fastreid/engine/train_loop.py#L871
・RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 2048, 3, 3], but got 2-dimensional input of size [48, 2048] instead
